import type { CatalogService } from './types'

export const AUTOMATION: CatalogService[] = [
  {
    sku: 'auto-lead-notify',
    name: 'Lead Notification Setup',
    tier: 'upgrade',
    category: 'automation',
    priceLabel: '$149',
    priceCents: 14_900,
    kind: 'one_time',
    included: ['Send form leads to email inboxes'],
    notIncluded: ['CRM routing', 'SMS notifications', 'Advanced workflows'],
    scopeBoundary: 'Up to 2 email recipients.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'auto-form-routing',
    name: 'Contact Form Routing',
    tier: 'upgrade',
    category: 'automation',
    priceLabel: '$249',
    priceCents: 24_900,
    kind: 'one_time',
    included: [
      'Route submissions by service, department, or location',
    ],
    notIncluded: [
      'CRM pipelines',
      'Complex conditional logic',
      'Custom backend',
    ],
    scopeBoundary: 'Up to 3 routing rules.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'auto-zapier',
    name: 'Zapier/Make Automation',
    tier: 'upgrade',
    category: 'automation',
    priceLabel: 'From $299',
    priceCents: 29_900,
    kind: 'one_time',
    included: [
      'One basic automation between website form and another app',
    ],
    notIncluded: [
      'Complex multi-step workflows',
      'Paid app subscriptions',
    ],
    scopeBoundary:
      'Final price depends on apps and number of steps. Scoped before checkout if complex.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'auto-crm',
    name: 'CRM Integration',
    tier: 'upgrade',
    category: 'automation',
    priceLabel: 'From $399',
    priceCents: 39_900,
    kind: 'one_time',
    included: [
      'Connect website form to CRM (HubSpot, Zoho, or similar)',
    ],
    notIncluded: [
      'CRM cleanup',
      'Pipeline strategy',
      'Complex sales automations',
    ],
    scopeBoundary:
      'Client provides CRM access. Third-party limitations may apply.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'auto-custom-workflow',
    name: 'Custom Workflow',
    tier: 'upgrade',
    category: 'automation',
    priceLabel: 'From $499',
    priceCents: 49_900,
    kind: 'one_time',
    included: [
      'Custom lead flow, notifications, tagging, or intake process',
    ],
    notIncluded: [
      'Full software product',
      'Client portal',
      'Dashboard',
    ],
    scopeBoundary:
      'Scoped after review. Requires written scope before work starts.',
    checkoutEnabled: false,
    projectType: 'web',
  },
]

export const BRANDING: CatalogService[] = [
  {
    sku: 'brand-logo-cleanup',
    name: 'Basic Logo Cleanup',
    tier: 'upgrade',
    category: 'branding',
    priceLabel: '$149',
    priceCents: 14_900,
    kind: 'one_time',
    included: [
      'Clean up existing logo file',
      'Improve sizing',
      'Export web-ready versions',
    ],
    notIncluded: [
      'New logo concept',
      'Full rebrand',
      'Illustration',
    ],
    scopeBoundary: 'Client must provide existing logo.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'brand-logo-simple',
    name: 'Simple Logo Design',
    tier: 'upgrade',
    category: 'branding',
    priceLabel: '$399',
    priceCents: 39_900,
    kind: 'one_time',
    included: [
      'Simple text/icon logo',
      '2 initial concepts',
      '1 revision round',
      'Web-ready files',
    ],
    notIncluded: [
      'Full brand identity',
      'Complex illustration',
      'Trademark research',
    ],
    scopeBoundary: 'Lightweight logo design only.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'brand-style-kit',
    name: 'Brand Color/Font Kit',
    tier: 'upgrade',
    category: 'branding',
    priceLabel: '$249',
    priceCents: 24_900,
    kind: 'one_time',
    included: [
      'Select website colors, fonts',
      'Simple style direction',
    ],
    notIncluded: [
      'Full brand strategy',
      'Print design',
      'Brand book',
    ],
    scopeBoundary: 'Website-focused style kit.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'brand-social-graphics',
    name: 'Social Profile Graphics',
    tier: 'upgrade',
    category: 'branding',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      'Profile image/banner formatting for up to 3 platforms',
    ],
    notIncluded: [
      'Social media management',
      'Post design',
      'Ad creatives',
    ],
    scopeBoundary: 'Uses existing brand assets.',
    checkoutEnabled: true,
    projectType: 'web',
  },
]

export const ADVANCED_PROJECTS: CatalogService[] = [
  {
    sku: 'adv-ecommerce',
    name: 'Ecommerce Setup',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $999',
    priceCents: null,
    kind: 'one_time',
    included: [
      'Product/shop setup',
      'Basic checkout integration',
      'Basic product layout',
    ],
    notIncluded: [
      'Large catalogs',
      'Custom shipping logic',
      'Subscriptions',
      'ERP integration',
    ],
    scopeBoundary:
      'Scoped based on products, platform, and payment needs.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-client-portal',
    name: 'Client Portal',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $2,500',
    priceCents: null,
    kind: 'one_time',
    included: [
      'Login-based area',
      'Basic dashboard',
      'Protected pages',
    ],
    notIncluded: [
      'Full SaaS platform',
      'Complex permissions',
      'Billing system',
    ],
    scopeBoundary: 'Requires discovery and written scope.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-dashboard',
    name: 'Custom Dashboard',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $2,500',
    priceCents: null,
    kind: 'one_time',
    included: ['Basic admin or reporting dashboard'],
    notIncluded: [
      'Full app development',
      'Complex data architecture',
    ],
    scopeBoundary: 'Scoped by data sources and features.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-membership',
    name: 'Membership System',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $1,499',
    priceCents: null,
    kind: 'one_time',
    included: ['Basic gated content or member access'],
    notIncluded: [
      'Community platform',
      'Custom billing',
      'Complex roles',
    ],
    scopeBoundary: 'Third-party platform may be used.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-booking-advanced',
    name: 'Advanced Booking System',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $1,499',
    priceCents: null,
    kind: 'one_time',
    included: ['More complex booking flow than basic embed'],
    notIncluded: [
      'Custom scheduling engine',
      'Staff logic',
      'Payments',
      'Reminders',
    ],
    scopeBoundary: 'Scoped based on business rules.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-api',
    name: 'API Integration',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $999',
    priceCents: null,
    kind: 'one_time',
    included: ['Connect website to third-party API'],
    notIncluded: [
      'Building or maintaining third-party API',
      'Complex backend systems',
    ],
    scopeBoundary:
      'Requires API documentation and access before final quote.',
    checkoutEnabled: false,
    projectType: 'web',
  },
  {
    sku: 'adv-custom-feature',
    name: 'Custom Web App Feature',
    tier: 'advanced',
    category: 'advanced',
    priceLabel: 'From $2,500',
    priceCents: null,
    kind: 'one_time',
    included: ['One custom feature beyond standard website build'],
    notIncluded: [
      'Full product build',
      'Mobile app',
      'SaaS architecture',
    ],
    scopeBoundary: 'Requires separate proposal.',
    checkoutEnabled: false,
    projectType: 'web',
  },
]
