import type { CatalogService } from './types'

export const COPYWRITING: CatalogService[] = [
  {
    sku: 'copy-homepage',
    name: 'Homepage Copy Rewrite',
    tier: 'upgrade',
    category: 'copywriting',
    priceLabel: '$299',
    priceCents: 29_900,
    kind: 'one_time',
    included: [
      'Homepage headline & intro rewrite',
      'Service blurbs & CTA text',
      'Trust copy',
    ],
    notIncluded: [
      'Full brand strategy',
      'Interviews',
      'Long-form sales copy',
    ],
    scopeBoundary:
      'Based on existing business info. Includes 1 revision round.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'copy-service-page',
    name: 'Service Page Copy',
    tier: 'upgrade',
    category: 'copywriting',
    priceLabel: '$149/page',
    priceCents: 14_900,
    kind: 'one_time',
    included: [
      'Up to 750 words for one service page',
      'Headline, sections, CTA',
      'Basic SEO phrasing',
    ],
    notIncluded: [
      'Deep research',
      'Technical manuals',
      'Legal/medical claims',
      'Advanced SEO',
    ],
    scopeBoundary:
      'Client must provide service details. Includes 1 revision round. One page per order.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'copy-site-pack',
    name: 'Full Site Copy Pack',
    tier: 'upgrade',
    category: 'copywriting',
    priceLabel: '$699',
    priceCents: 69_900,
    kind: 'one_time',
    included: [
      'Copy for up to 5 core pages',
      'Home, About, Services, Contact, one service page',
    ],
    notIncluded: [
      'Blog posts',
      'SEO page batches',
      'Brand naming',
      'Slogan packages',
    ],
    scopeBoundary:
      'Best for businesses with no usable website copy.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'copy-blog-single',
    name: 'Blog Post',
    tier: 'upgrade',
    category: 'copywriting',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      'One blog post',
      'Basic SEO formatting',
      'Image placement',
      'Title/meta',
    ],
    notIncluded: [
      'Expert interviews',
      'Original photography',
      'Advanced research',
      'Backlinking',
    ],
    scopeBoundary: 'Up to 1,000 words. Includes one edit pass.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'copy-blog-2mo',
    name: '2 Blog Posts Monthly',
    tier: 'upgrade',
    category: 'copywriting',
    priceLabel: '$399/mo',
    priceCents: 39_900,
    kind: 'recurring',
    interval: 'monthly',
    included: [
      '2 blog posts per month',
      'Basic SEO formatting',
      'Publishing',
    ],
    notIncluded: [
      'Full SEO campaign',
      'Custom graphics',
      'Backlinking',
      'Guaranteed rankings',
    ],
    scopeBoundary: 'Monthly content only. Unused posts do not roll over.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
]

export const LEAD_CONVERSION: CatalogService[] = [
  {
    sku: 'lead-quote-form',
    name: 'Quote Request Form',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$249',
    priceCents: 24_900,
    kind: 'one_time',
    included: [
      'Custom quote form',
      'Email delivery & thank-you message',
      'Mobile styling',
    ],
    notIncluded: ['CRM integration', 'Conditional logic', 'Payment collection'],
    scopeBoundary: 'Up to 10 fields. More complex forms are scoped separately.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'lead-multistep-form',
    name: 'Multi-Step Lead Form',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$399',
    priceCents: 39_900,
    kind: 'one_time',
    included: [
      'Multi-step form',
      'Basic conditional flow',
      'Email notifications',
    ],
    notIncluded: [
      'Complex pricing logic',
      'CRM automation',
      'Database storage',
    ],
    scopeBoundary: 'Up to 3 steps and 15 fields. Advanced logic is custom-scoped.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'lead-booking',
    name: 'Booking Setup',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$299',
    priceCents: 29_900,
    kind: 'one_time',
    included: [
      'Embed or connect Calendly, Acuity, Square, or similar',
    ],
    notIncluded: [
      'Custom booking software',
      'Payment rules',
      'Staff scheduling logic',
    ],
    scopeBoundary:
      'Uses third-party booking platform. Client pays third-party fees.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'lead-call-tracking',
    name: 'Call Tracking Setup',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      'Call tracking number setup',
      'Click-to-call tracking',
      'Basic placement',
    ],
    notIncluded: [
      'Call center setup',
      'Advanced reporting',
      'Ad attribution',
    ],
    scopeBoundary: 'Client pays any third-party call tracking fees.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'lead-auto-reply',
    name: 'Auto-Reply Email Setup',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: ['Basic email response after form submission'],
    notIncluded: [
      'Email marketing sequence',
      'CRM workflow',
      'Custom templates',
    ],
    scopeBoundary: 'One simple auto-response email.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'lead-review-request',
    name: 'Review Request Setup',
    tier: 'upgrade',
    category: 'lead-conversion',
    priceLabel: '$149',
    priceCents: 14_900,
    kind: 'one_time',
    included: ['Review CTA section or link to Google review page'],
    notIncluded: [
      'Review management software',
      'Reputation campaign',
    ],
    scopeBoundary: 'Client provides Google review link or access.',
    checkoutEnabled: true,
    projectType: 'web',
  },
]
