import type { CatalogService } from './types'

export const PAGE_UPGRADES: CatalogService[] = [
  {
    sku: 'page-extra-standard',
    name: 'Extra Standard Page',
    tier: 'upgrade',
    category: 'page-upgrade',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      '1 additional page, standard layout',
      'Mobile formatting',
      'Basic SEO title/meta',
      'CTA section',
    ],
    notIncluded: [
      'Copywriting from scratch',
      'Custom design',
      'Advanced SEO',
      'Custom forms',
      'Animations',
    ],
    scopeBoundary:
      'Up to 750 words. Client provides content or purchases copywriting. Includes 1 revision round.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'page-expansion-3',
    name: '3-Page Expansion Pack',
    tier: 'upgrade',
    category: 'page-upgrade',
    priceLabel: '$499',
    priceCents: 49_900,
    kind: 'one_time',
    included: [
      '3 standard pages',
      'Basic formatting & mobile layout',
      'SEO title/meta for each',
    ],
    notIncluded: [
      'Full content strategy',
      'Custom designs per page',
      'Advanced keyword research',
    ],
    scopeBoundary:
      'Best for service pages or simple informational pages. Up to 750 words per page.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'page-expansion-5',
    name: '5-Page Expansion Pack',
    tier: 'upgrade',
    category: 'page-upgrade',
    priceLabel: '$799',
    priceCents: 79_900,
    kind: 'one_time',
    included: [
      '5 standard pages',
      'Basic formatting & mobile layout',
      'SEO title/meta for each',
    ],
    notIncluded: [
      'Advanced SEO campaign',
      'Custom photography',
      'Heavy revisions',
    ],
    scopeBoundary:
      'Best for businesses adding multiple services or areas. Includes 1 revision round per batch.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'page-landing',
    name: 'Landing Page Build',
    tier: 'upgrade',
    category: 'page-upgrade',
    priceLabel: '$499',
    priceCents: 49_900,
    kind: 'one_time',
    included: [
      '1 focused landing page',
      'CTA section',
      'Form or button',
      'Mobile layout',
      'Basic SEO setup',
    ],
    notIncluded: [
      'Paid ads management',
      'A/B testing',
      'Advanced copywriting',
      'CRM automation',
    ],
    scopeBoundary:
      'Designed for one offer, one campaign, or one service. Includes 1 revision round.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'page-sales',
    name: 'Sales Page Build',
    tier: 'upgrade',
    category: 'page-upgrade',
    priceLabel: '$799',
    priceCents: 79_900,
    kind: 'one_time',
    included: [
      'Longer conversion-focused page',
      'Offer, trust, FAQ & CTA sections',
    ],
    notIncluded: [
      'Long-form copy from scratch',
      'Funnel automation',
      'Payment setup',
    ],
    scopeBoundary:
      'Best for premium offers. Copywriting may be quoted separately if client has no content.',
    checkoutEnabled: true,
    projectType: 'web',
  },
]

export const SEO_CONTENT_BUNDLES: CatalogService[] = [
  {
    sku: 'seo-pages-5',
    name: '5 SEO Content Pages',
    tier: 'upgrade',
    category: 'seo-content',
    priceLabel: '$499',
    priceCents: 49_900,
    kind: 'one_time',
    included: [
      '5 templated SEO pages',
      'Basic keyword targeting',
      'Metadata & internal links',
      'Image placement',
    ],
    notIncluded: [
      'Deep custom copy',
      'Advanced research',
      'Backlinks',
      'Guaranteed rankings',
    ],
    scopeBoundary:
      'Best for city/service pages or blog-style content. Uses repeatable layout system.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'seo-pages-10',
    name: '10 SEO Content Pages',
    tier: 'upgrade',
    category: 'seo-content',
    priceLabel: '$899',
    priceCents: 89_900,
    kind: 'one_time',
    included: [
      '10 SEO pages',
      'Basic keyword structure',
      'Metadata & internal linking plan',
    ],
    notIncluded: [
      'Full SEO campaign',
      'Custom graphics',
      'Advanced competitor research',
    ],
    scopeBoundary: 'Includes light strategy and publishing. Major custom sections are not included.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'seo-pages-25',
    name: '25 SEO Content Pages',
    tier: 'upgrade',
    category: 'seo-content',
    priceLabel: '$1,999',
    priceCents: 199_900,
    kind: 'one_time',
    included: [
      '25 repeatable content pages',
      'Metadata & internal linking',
      'Basic image matching',
    ],
    notIncluded: [
      'Heavy manual design',
      'Unique custom layout per page',
      'Link building',
    ],
    scopeBoundary:
      'Best for scaling service-area or blog content. Template-based production.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'seo-pages-50',
    name: '50 SEO Content Pages',
    tier: 'upgrade',
    category: 'seo-content',
    priceLabel: '$3,499',
    priceCents: 349_900,
    kind: 'one_time',
    included: [
      '50 repeatable SEO pages',
      'Metadata, image placement',
      'Internal linking',
    ],
    notIncluded: [
      'Guaranteed traffic',
      'Backlink outreach',
      'Advanced analytics reporting',
    ],
    scopeBoundary: 'Requires approved page list before production starts.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'seo-pages-100',
    name: '100 SEO Content Pages',
    tier: 'upgrade',
    category: 'seo-content',
    priceLabel: '$5,999',
    priceCents: 599_900,
    kind: 'one_time',
    included: [
      '100 repeatable SEO pages',
      'Bulk content structure',
      'Metadata & publishing support',
    ],
    notIncluded: [
      'Unique design per page',
      'High-touch revisions',
      'Full SEO retainer work',
    ],
    scopeBoundary:
      'Bulk content project. Includes agreed structure and limited revision pass.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
]
