import type { CatalogService } from './types'

export const WEBSITE_PLANS: CatalogService[] = [
  {
    sku: 'plan-hosting',
    name: 'Hosting',
    tier: 'plan',
    category: 'website-plan',
    priceLabel: '$50/mo',
    priceCents: 50_00,
    kind: 'recurring',
    interval: 'monthly',
    bestFor: 'Basic hosting',
    included: ['Hosting & SSL'],
    notIncluded: ['Edits'],
    scopeBoundary: 'Hosting only.',
    checkoutEnabled: true,
    projectType: 'hosting',
  },
  {
    sku: 'plan-analytics',
    name: 'Analytics',
    tier: 'plan',
    category: 'website-plan',
    priceLabel: '$50/mo',
    priceCents: 50_00,
    kind: 'recurring',
    interval: 'monthly',
    bestFor: 'Basic analytics',
    included: ['Analytics'],
    notIncluded: ['Edits'],
    scopeBoundary: 'Analytics only.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'plan-launch',
    name: 'Launch Website Plan',
    tier: 'plan',
    category: 'website-plan',
    priceLabel: '$149/mo',
    priceCents: 14_900,
    kind: 'recurring',
    interval: 'monthly',
    bestFor: 'Simple businesses that need a clean online presence',
    included: [
      'Up to 3 pages',
      'Hosting & SSL',
      'Mobile-friendly design',
      'Contact form',
      'Click-to-call buttons',
      'Basic SEO setup',
      'Basic speed optimization',
      '30 minutes of monthly edits',
    ],
    notIncluded: [
      'Copywriting from scratch',
      'Blogs',
      'SEO campaigns',
      'Booking systems',
      'Custom automations',
      'Ecommerce',
      'Extra pages',
    ],
    scopeBoundary:
      'Includes one initial website build using Nexrena’s standard layout system. Major redesigns or new pages are add-ons.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'plan-growth',
    name: 'Growth Website Plan',
    tier: 'plan',
    category: 'website-plan',
    priceLabel: '$249/mo',
    priceCents: 24_900,
    kind: 'recurring',
    interval: 'monthly',
    bestFor: 'Most local businesses that want a stronger website for calls and leads',
    badge: 'Recommended',
    included: [
      'Up to 5 pages',
      'Everything in Launch',
      'Improved homepage layout',
      'Service sections',
      'Review/testimonial section',
      'Google Analytics & Search Console setup',
      '60 minutes of monthly edits',
    ],
    notIncluded: [
      'Advanced SEO',
      'Blog writing',
      'CRM integrations',
      'Booking systems',
      'Sales funnels',
      'Ecommerce',
      'Custom portals',
    ],
    scopeBoundary:
      'Includes one stronger local business website. Extra pages, advanced features, and ongoing content are add-ons.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'plan-lead-engine',
    name: 'Lead Engine Plan',
    tier: 'plan',
    category: 'website-plan',
    priceLabel: '$399/mo+',
    priceCents: 39_900,
    kind: 'recurring',
    interval: 'monthly',
    bestFor: 'Businesses that want ongoing growth, more pages, and optimization',
    included: [
      'Up to 8 pages',
      'Everything in Growth',
      'Priority support',
      'Monthly conversion review',
      'SEO page planning',
      'Analytics review',
      '120 minutes of monthly edits',
    ],
    notIncluded: [
      'Full SEO campaign',
      'Paid ads',
      'Ecommerce',
      'Complex integrations',
      'Custom dashboards',
      'Large content systems',
    ],
    scopeBoundary:
      'Includes website care and growth support. New page builds, large SEO content batches, and integrations are priced separately.',
    checkoutEnabled: true,
    projectType: 'web',
  },
]
