import type { CatalogService } from './types'

export const TRUST_DESIGN: CatalogService[] = [
  {
    sku: 'trust-reviews',
    name: 'Review/Testimonial Section',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$149',
    priceCents: 14_900,
    kind: 'one_time',
    included: ['Testimonial section with up to 6 reviews'],
    notIncluded: [
      'Collecting reviews',
      'Video testimonial editing',
      'Review software',
    ],
    scopeBoundary: 'Client provides review text or links.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'trust-gallery',
    name: 'Before/After Gallery',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: ['Gallery section with up to 12 images'],
    notIncluded: [
      'Photo editing',
      'Image sourcing',
      'Custom filtering system',
    ],
    scopeBoundary: 'Client provides images. Extra image cleanup is separate.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'trust-pricing',
    name: 'Pricing/Menu Section',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: ['Pricing table or menu section, up to 3 packages/categories'],
    notIncluded: [
      'Full ecommerce checkout',
      'Dynamic pricing',
      'Custom calculator',
    ],
    scopeBoundary: 'Static pricing/menu display only.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'trust-faq',
    name: 'FAQ Section',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$149',
    priceCents: 14_900,
    kind: 'one_time',
    included: [
      'Up to 8 FAQs',
      'Styled section',
      'Basic FAQ schema if appropriate',
    ],
    notIncluded: [
      'Writing complex legal/medical answers',
      'Advanced SEO research',
    ],
    scopeBoundary:
      'Client provides rough answers or purchases copywriting.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'trust-photo-source',
    name: 'Photo Sourcing Pack',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      'Find and place stock images matching brand/style',
    ],
    notIncluded: [
      'Custom photography',
      'AI image campaigns',
      'Premium stock licensing above basic stock',
    ],
    scopeBoundary: 'Up to 10 sourced images.',
    checkoutEnabled: true,
    projectType: 'web',
  },
  {
    sku: 'trust-image-edit',
    name: 'Image Editing Pack',
    tier: 'upgrade',
    category: 'trust-design',
    priceLabel: '$249',
    priceCents: 24_900,
    kind: 'one_time',
    included: [
      'Basic cropping, resizing, cleanup, compression',
    ],
    notIncluded: [
      'Advanced Photoshop work',
      'Product retouching',
      'Custom graphics',
    ],
    scopeBoundary: 'Up to 15 images.',
    checkoutEnabled: true,
    projectType: 'web',
  },
]

export const LOCAL_SEO: CatalogService[] = [
  {
    sku: 'local-seo-setup',
    name: 'Local SEO Setup',
    tier: 'upgrade',
    category: 'local-seo',
    priceLabel: '$399',
    priceCents: 39_900,
    kind: 'one_time',
    included: [
      'Basic keyword mapping',
      'Page titles & meta descriptions',
      'Heading cleanup',
      'Sitemap check',
      'Search Console setup',
    ],
    notIncluded: [
      'Monthly SEO campaign',
      'Backlinks',
      'Blog writing',
      'Guaranteed rankings',
    ],
    scopeBoundary: 'One-time setup only.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'local-gbp-cleanup',
    name: 'Google Business Profile Cleanup',
    tier: 'upgrade',
    category: 'local-seo',
    priceLabel: '$199',
    priceCents: 19_900,
    kind: 'one_time',
    included: [
      'Review profile info',
      'Suggest categories',
      'Update description/services if access provided',
    ],
    notIncluded: [
      'Ongoing GBP posting',
      'Review management',
      'Suspension fixes',
    ],
    scopeBoundary:
      'Client must provide access. Google approval is not guaranteed.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'local-pages-3',
    name: '3 Local SEO Pages',
    tier: 'upgrade',
    category: 'local-seo',
    priceLabel: '$699',
    priceCents: 69_900,
    kind: 'one_time',
    included: [
      '3 city/service pages',
      'Basic local SEO copy',
      'Metadata & internal links',
    ],
    notIncluded: [
      'Advanced competitor research',
      'Link building',
      'Unique design per page',
    ],
    scopeBoundary: 'Best for targeting nearby service areas.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'local-pages-5',
    name: '5 Local SEO Pages',
    tier: 'upgrade',
    category: 'local-seo',
    priceLabel: '$999',
    priceCents: 99_900,
    kind: 'one_time',
    included: [
      '5 city/service pages',
      'Metadata, basic image placement',
      'Internal links',
    ],
    notIncluded: [
      'Guaranteed rankings',
      'Custom photography',
      'Advanced SEO campaign',
    ],
    scopeBoundary: 'Uses repeatable local page format.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
  {
    sku: 'local-pages-10',
    name: '10 Local SEO Pages',
    tier: 'upgrade',
    category: 'local-seo',
    priceLabel: '$1,799',
    priceCents: 179_900,
    kind: 'one_time',
    included: [
      '10 city/service pages',
      'Metadata, internal links',
      'Publishing',
    ],
    notIncluded: [
      'Full SEO retainer',
      'Backlink strategy',
      'Heavy revisions',
    ],
    scopeBoundary:
      'Requires approved target city/service list before work begins.',
    checkoutEnabled: true,
    projectType: 'seo',
  },
]
