import type { KnowledgeChunk } from '../types'

export const faqKnowledge: KnowledgeChunk[] = [
  {
    id: 'faq-redesign-timeline',
    category: 'faq',
    title: 'B2B redesign timeline',
    content: 'Most B2B website redesigns run 8–12 weeks from kickoff to launch depending on content strategy, design rounds, development, and migration. Detailed schedule provided at project start.',
    keywords: ['how long', 'timeline', 'redesign', 'weeks', 'launch'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-manufacturers',
    category: 'faq',
    title: 'Manufacturing clients',
    content: 'Yes — we specialize in manufacturing, e-commerce, and professional services. We understand technical buyers, complex product catalogs, and information architecture for procurement intent.',
    keywords: ['manufacturer', 'industrial', 'factory', 'catalog'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-seo-include',
    category: 'faq',
    title: 'What SEO includes',
    content: 'Technical SEO audit, keyword research, on-page optimization, content strategy, ongoing monitoring. Focus on sustainable organic growth — fixes shipped to production, not shelfware reports.',
    keywords: ['what includes', 'seo package', 'deliverables'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-rankings-migration',
    category: 'faq',
    title: 'Redesign without losing rankings',
    content: 'Yes — migration best practices: preserve URLs where possible, redirect mapping, maintain internal linking, monitor rankings post-launch. Forzabuilt is a reference: 200+ SKU WordPress→Astro migration without indexing collapse.',
    keywords: ['rankings', 'lose', 'migration', 'redirect', 'seo loss'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-waas-vs-diy',
    category: 'faq',
    title: 'WaaS vs Wix/Squarespace',
    content: 'DIY builders are cheap but you do design, setup, updates, and fixes yourself. Nexrena WaaS is managed: we design, build, host, maintain, and support so the site stays fast, secure, and effective.',
    keywords: ['wix', 'squarespace', 'diy', 'godaddy', 'cheap website'],
    source: 'nexrena.com/pricing',
  },
  {
    id: 'faq-support-after-launch',
    category: 'faq',
    title: 'Ongoing support',
    content: 'Yes — WaaS includes ongoing care. Project clients can move to retainer for content updates, SEO monitoring, and technical support. Many start with a project and continue as partners.',
    keywords: ['support', 'after launch', 'maintenance', 'retainer', 'ongoing'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-effective-b2b',
    category: 'faq',
    title: 'Effective B2B website',
    content: 'Clear value proposition, strong information architecture, content for technical buyers, fast performance, conversion paths to contact or demo. Measurable — not just pretty.',
    keywords: ['effective', 'good website', 'what makes', 'b2b site'],
    source: 'nexrena.com/resources/faq',
  },
  {
    id: 'faq-hosting',
    category: 'faq',
    title: 'Hosting',
    content: 'WaaS includes hosting, SSL, security, and maintenance. Custom builds typically deploy on Vercel or client-preferred infrastructure — we handle setup and handoff documentation.',
    keywords: ['hosting', 'server', 'ssl', 'domain', 'vercel'],
    source: 'nexrena.com/pricing',
  },
  {
    id: 'faq-local-seo',
    category: 'faq',
    title: 'Local SEO',
    content: 'Local SEO upgrades available: local landing pages, Google Business Profile cleanup, metadata, local citations. Furniture Packages USA example: local SEO for Florida real estate procurement markets.',
    keywords: ['local seo', 'local search', 'near me', 'geo'],
    source: 'nexrena.com/pricing',
  },
  {
    id: 'faq-gbp',
    category: 'faq',
    title: 'Google Business Profile',
    content: 'Google Business Profile optimization is available as part of local SEO upgrades and Growth/Lead Engine WaaS tiers include Search Console setup. We help with profile cleanup, categories, and local page alignment — not a standalone GBP-only microservice.',
    keywords: ['google business', 'gbp', 'google maps', 'business profile'],
    source: 'nexrena.com/pricing',
  },
]
